services:
  postgresql:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking-app
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
